// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: donor.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDonor = `-- name: CreateDonor :one
INSERT INTO core.donor (
    donor_name,
    phone_number
) VALUES (
    $1, $2
)
RETURNING id, donor_name, phone_number
`

type CreateDonorParams struct {
	DonorName   string `json:"donor_name"`
	PhoneNumber string `json:"phone_number"`
}

// Insert a new donor
func (q *Queries) CreateDonor(ctx context.Context, arg CreateDonorParams) (CoreDonor, error) {
	row := q.db.QueryRow(ctx, createDonor, arg.DonorName, arg.PhoneNumber)
	var i CoreDonor
	err := row.Scan(&i.ID, &i.DonorName, &i.PhoneNumber)
	return i, err
}

const searchDonors = `-- name: SearchDonors :many
SELECT id, donor_name, phone_number
FROM core.donor
WHERE donor_name ILIKE '%' || $1 || '%' OR phone_number ILIKE '%' || $1 || '%'
ORDER BY donor_name
`

// Search donors by name or phone number
func (q *Queries) SearchDonors(ctx context.Context, dollar_1 pgtype.Text) ([]CoreDonor, error) {
	rows, err := q.db.Query(ctx, searchDonors, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDonor{}
	for rows.Next() {
		var i CoreDonor
		if err := rows.Scan(&i.ID, &i.DonorName, &i.PhoneNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
