// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: donor.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDonor = `-- name: CreateDonor :one
INSERT INTO core.donor (
    donor_name,
    phone_number
) VALUES (
    $1, $2
)
RETURNING id, donor_name, phone_number
`

type CreateDonorParams struct {
	DonorName   string `json:"donor_name"`
	PhoneNumber string `json:"phone_number"`
}

// Insert a new donor
func (q *Queries) CreateDonor(ctx context.Context, arg CreateDonorParams) (CoreDonor, error) {
	row := q.db.QueryRow(ctx, createDonor, arg.DonorName, arg.PhoneNumber)
	var i CoreDonor
	err := row.Scan(&i.ID, &i.DonorName, &i.PhoneNumber)
	return i, err
}

const getDonor = `-- name: GetDonor :one
SELECT id, donor_name, phone_number
FROM core.donor
WHERE id = $1
`

// Get a single donor by ID
func (q *Queries) GetDonor(ctx context.Context, id string) (CoreDonor, error) {
	row := q.db.QueryRow(ctx, getDonor, id)
	var i CoreDonor
	err := row.Scan(&i.ID, &i.DonorName, &i.PhoneNumber)
	return i, err
}

const getDonorByPhoneNumber = `-- name: GetDonorByPhoneNumber :one
SELECT id, donor_name, phone_number
FROM core.donor
WHERE phone_number = $1
`

// Get a donor by phone_number
func (q *Queries) GetDonorByPhoneNumber(ctx context.Context, phoneNumber string) (CoreDonor, error) {
	row := q.db.QueryRow(ctx, getDonorByPhoneNumber, phoneNumber)
	var i CoreDonor
	err := row.Scan(&i.ID, &i.DonorName, &i.PhoneNumber)
	return i, err
}

const getDonorWithTreeCount = `-- name: GetDonorWithTreeCount :one
SELECT 
    d.id,
    d.donor_name,
    d.phone_number,
    COUNT(t.id) as tree_count
FROM core.donor d
LEFT JOIN core.tree t ON d.id = t.donor_id
WHERE d.id = $1
GROUP BY d.id, d.donor_name, d.phone_number
`

type GetDonorWithTreeCountRow struct {
	ID          string `json:"id"`
	DonorName   string `json:"donor_name"`
	PhoneNumber string `json:"phone_number"`
	TreeCount   int64  `json:"tree_count"`
}

// Get donor with their tree count
func (q *Queries) GetDonorWithTreeCount(ctx context.Context, id string) (GetDonorWithTreeCountRow, error) {
	row := q.db.QueryRow(ctx, getDonorWithTreeCount, id)
	var i GetDonorWithTreeCountRow
	err := row.Scan(
		&i.ID,
		&i.DonorName,
		&i.PhoneNumber,
		&i.TreeCount,
	)
	return i, err
}

const listDonors = `-- name: ListDonors :many
SELECT id, donor_name, phone_number
FROM core.donor
ORDER BY donor_name
`

// Get all donors
func (q *Queries) ListDonors(ctx context.Context) ([]CoreDonor, error) {
	rows, err := q.db.Query(ctx, listDonors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDonor{}
	for rows.Next() {
		var i CoreDonor
		if err := rows.Scan(&i.ID, &i.DonorName, &i.PhoneNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDonorsWithTreeCounts = `-- name: ListDonorsWithTreeCounts :many
SELECT 
    d.id,
    d.donor_name,
    d.phone_number,
    COUNT(t.id) as tree_count
FROM core.donor d
LEFT JOIN core.tree t ON d.id = t.donor_id
GROUP BY d.id, d.donor_name, d.phone_number
ORDER BY tree_count DESC, d.donor_name
`

type ListDonorsWithTreeCountsRow struct {
	ID          string `json:"id"`
	DonorName   string `json:"donor_name"`
	PhoneNumber string `json:"phone_number"`
	TreeCount   int64  `json:"tree_count"`
}

// Get all donors with their tree counts
func (q *Queries) ListDonorsWithTreeCounts(ctx context.Context) ([]ListDonorsWithTreeCountsRow, error) {
	rows, err := q.db.Query(ctx, listDonorsWithTreeCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDonorsWithTreeCountsRow{}
	for rows.Next() {
		var i ListDonorsWithTreeCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.DonorName,
			&i.PhoneNumber,
			&i.TreeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDonors = `-- name: SearchDonors :many
SELECT id, donor_name, phone_number
FROM core.donor
WHERE donor_name ILIKE '%' || $1 || '%' OR phone_number ILIKE '%' || $1 || '%'
ORDER BY donor_name
`

// Search donors by name or phone number
func (q *Queries) SearchDonors(ctx context.Context, dollar_1 pgtype.Text) ([]CoreDonor, error) {
	rows, err := q.db.Query(ctx, searchDonors, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreDonor{}
	for rows.Next() {
		var i CoreDonor
		if err := rows.Scan(&i.ID, &i.DonorName, &i.PhoneNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDonor = `-- name: UpdateDonor :one
UPDATE core.donor
SET 
    donor_name = $2,
    phone_number = $3
WHERE id = $1
RETURNING id, donor_name, phone_number
`

type UpdateDonorParams struct {
	ID          string `json:"id"`
	DonorName   string `json:"donor_name"`
	PhoneNumber string `json:"phone_number"`
}

// Update donor information
func (q *Queries) UpdateDonor(ctx context.Context, arg UpdateDonorParams) (CoreDonor, error) {
	row := q.db.QueryRow(ctx, updateDonor, arg.ID, arg.DonorName, arg.PhoneNumber)
	var i CoreDonor
	err := row.Scan(&i.ID, &i.DonorName, &i.PhoneNumber)
	return i, err
}
