// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreDonor struct {
	ID          string `json:"id"`
	DonorName   string `json:"donor_name"`
	PhoneNumber string `json:"phone_number"`
}

type CoreFile struct {
	ID             string             `json:"id"`
	FileStore      string             `json:"file_store"`
	FileStoreID    pgtype.Text        `json:"file_store_id"`
	FilePath       pgtype.Text        `json:"file_path"`
	FileName       pgtype.Text        `json:"file_name"`
	FileType       pgtype.Text        `json:"file_type"`
	FileExpiration pgtype.Timestamptz `json:"file_expiration"`
}

type CoreProject struct {
	ProjectName string `json:"project_name"`
	Metadata    []byte `json:"metadata"`
	ProjectCode string `json:"project_code"`
}

type CoreTree struct {
	ID           string             `json:"id"`
	ProjectCode  string             `json:"project_code"`
	TreeNumber   int32              `json:"tree_number"`
	DonorID      string             `json:"donor_id"`
	TreeLocation interface{}        `json:"tree_location"`
	PlantedAt    pgtype.Timestamptz `json:"planted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Metadata     []byte             `json:"metadata"`
}

type CoreTreeUpdate struct {
	TreeID     string             `json:"tree_id"`
	UpdateDate pgtype.Timestamptz `json:"update_date"`
	FileID     string             `json:"file_id"`
}
