// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO core.project (
    project_code,
    project_name,
    metadata
) VALUES (
    $1, $2, $3
)
RETURNING project_name, metadata, project_code
`

type CreateProjectParams struct {
	ProjectCode string `json:"project_code"`
	ProjectName string `json:"project_name"`
	Metadata    []byte `json:"metadata"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CoreProject, error) {
	row := q.db.QueryRow(ctx, createProject, arg.ProjectCode, arg.ProjectName, arg.Metadata)
	var i CoreProject
	err := row.Scan(&i.ProjectName, &i.Metadata, &i.ProjectCode)
	return i, err
}

const searchProjects = `-- name: SearchProjects :many
SELECT project_name, metadata, project_code
FROM core.project
WHERE project_name ILIKE '%' || $1 || '%' OR project_code ILIKE '%' || $1 || '%'
ORDER BY project_name
`

func (q *Queries) SearchProjects(ctx context.Context, dollar_1 pgtype.Text) ([]CoreProject, error) {
	rows, err := q.db.Query(ctx, searchProjects, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreProject{}
	for rows.Next() {
		var i CoreProject
		if err := rows.Scan(&i.ProjectName, &i.Metadata, &i.ProjectCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
