// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Insert a new donor
	CreateDonor(ctx context.Context, arg CreateDonorParams) (CoreDonor, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (CoreProject, error)
	// Insert a new tree
	CreateTree(ctx context.Context, arg CreateTreeParams) (CreateTreeRow, error)
	// Insert a new tree update
	CreateTreeUpdate(ctx context.Context, arg CreateTreeUpdateParams) (CoreTreeUpdate, error)
	// Get detailed statistics for a project cluster
	GetClusterDetail(ctx context.Context, projectCode string) (GetClusterDetailRow, error)
	// Get the most recent update for a tree
	GetLatestTreeUpdate(ctx context.Context, treeID string) (GetLatestTreeUpdateRow, error)
	GetLatestTreeUpdateFile(ctx context.Context, treeID string) (GetLatestTreeUpdateFileRow, error)
	// Get a single tree by ID with full details
	GetTreeByID(ctx context.Context, id string) (GetTreeByIDRow, error)
	// Get a single tree by project code and tree number
	GetTreeByProjectCodeAndNumber(ctx context.Context, arg GetTreeByProjectCodeAndNumberParams) (GetTreeByProjectCodeAndNumberRow, error)
	// Search donors by name or phone number
	SearchDonors(ctx context.Context, dollar_1 pgtype.Text) ([]CoreDonor, error)
	SearchProjects(ctx context.Context, dollar_1 pgtype.Text) ([]CoreProject, error)
	UpsertFile(ctx context.Context, arg UpsertFileParams) (UpsertFileRow, error)
}

var _ Querier = (*Queries)(nil)
