// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: town.sql

package db

import (
	"context"
)

const createTown = `-- name: CreateTown :one
INSERT INTO core.town (
    town_code,
    town_name,
    metadata
) VALUES (
    $1, $2, $3
)
RETURNING town_name, metadata, town_code
`

type CreateTownParams struct {
	TownCode string `json:"town_code"`
	TownName string `json:"town_name"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) CreateTown(ctx context.Context, arg CreateTownParams) (CoreTown, error) {
	row := q.db.QueryRow(ctx, createTown, arg.TownCode, arg.TownName, arg.Metadata)
	var i CoreTown
	err := row.Scan(&i.TownName, &i.Metadata, &i.TownCode)
	return i, err
}

const deleteTown = `-- name: DeleteTown :exec
DELETE FROM core.town
WHERE town_code = $1
`

func (q *Queries) DeleteTown(ctx context.Context, townCode string) error {
	_, err := q.db.Exec(ctx, deleteTown, townCode)
	return err
}

const getTown = `-- name: GetTown :one
SELECT town_name, metadata, town_code FROM core.town
WHERE town_code = $1
`

func (q *Queries) GetTown(ctx context.Context, townCode string) (CoreTown, error) {
	row := q.db.QueryRow(ctx, getTown, townCode)
	var i CoreTown
	err := row.Scan(&i.TownName, &i.Metadata, &i.TownCode)
	return i, err
}

const getTownWithTreeCount = `-- name: GetTownWithTreeCount :one
SELECT 
    t.town_code,
    t.town_name,
    t.metadata,
    COUNT(tr.id) as tree_count
FROM core.town t
LEFT JOIN core.tree tr ON t.town_code = tr.town_code
WHERE t.town_code = $1
GROUP BY t.town_code, t.town_name, t.metadata
`

type GetTownWithTreeCountRow struct {
	TownCode  string `json:"town_code"`
	TownName  string `json:"town_name"`
	Metadata  []byte `json:"metadata"`
	TreeCount int64  `json:"tree_count"`
}

func (q *Queries) GetTownWithTreeCount(ctx context.Context, townCode string) (GetTownWithTreeCountRow, error) {
	row := q.db.QueryRow(ctx, getTownWithTreeCount, townCode)
	var i GetTownWithTreeCountRow
	err := row.Scan(
		&i.TownCode,
		&i.TownName,
		&i.Metadata,
		&i.TreeCount,
	)
	return i, err
}

const listTowns = `-- name: ListTowns :many
SELECT town_name, metadata, town_code FROM core.town
ORDER BY town_name
`

func (q *Queries) ListTowns(ctx context.Context) ([]CoreTown, error) {
	rows, err := q.db.Query(ctx, listTowns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoreTown{}
	for rows.Next() {
		var i CoreTown
		if err := rows.Scan(&i.TownName, &i.Metadata, &i.TownCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTownsWithTreeCounts = `-- name: ListTownsWithTreeCounts :many
SELECT 
    t.town_code,
    t.town_name,
    t.metadata,
    COUNT(tr.id) as tree_count
FROM core.town t
LEFT JOIN core.tree tr ON t.town_code = tr.town_code
GROUP BY t.town_code, t.town_name, t.metadata
ORDER BY t.town_name
`

type ListTownsWithTreeCountsRow struct {
	TownCode  string `json:"town_code"`
	TownName  string `json:"town_name"`
	Metadata  []byte `json:"metadata"`
	TreeCount int64  `json:"tree_count"`
}

func (q *Queries) ListTownsWithTreeCounts(ctx context.Context) ([]ListTownsWithTreeCountsRow, error) {
	rows, err := q.db.Query(ctx, listTownsWithTreeCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTownsWithTreeCountsRow{}
	for rows.Next() {
		var i ListTownsWithTreeCountsRow
		if err := rows.Scan(
			&i.TownCode,
			&i.TownName,
			&i.Metadata,
			&i.TreeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTown = `-- name: UpdateTown :one
UPDATE core.town
SET 
    town_name = $2,
    metadata = $3
WHERE town_code = $1
RETURNING town_name, metadata, town_code
`

type UpdateTownParams struct {
	TownCode string `json:"town_code"`
	TownName string `json:"town_name"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) UpdateTown(ctx context.Context, arg UpdateTownParams) (CoreTown, error) {
	row := q.db.QueryRow(ctx, updateTown, arg.TownCode, arg.TownName, arg.Metadata)
	var i CoreTown
	err := row.Scan(&i.TownName, &i.Metadata, &i.TownCode)
	return i, err
}
