// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tree_update.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTreeUpdate = `-- name: CreateTreeUpdate :one
INSERT INTO
    core.tree_update (tree_id, file_id)
VALUES ($1, $2) ON CONFLICT (file_id) DO
UPDATE
SET
    file_id = EXCLUDED.file_id RETURNING tree_id,
    update_date,
    file_id
`

type CreateTreeUpdateParams struct {
	TreeID string `json:"tree_id"`
	FileID string `json:"file_id"`
}

// Insert a new tree update
func (q *Queries) CreateTreeUpdate(ctx context.Context, arg CreateTreeUpdateParams) (CoreTreeUpdate, error) {
	row := q.db.QueryRow(ctx, createTreeUpdate, arg.TreeID, arg.FileID)
	var i CoreTreeUpdate
	err := row.Scan(&i.TreeID, &i.UpdateDate, &i.FileID)
	return i, err
}

const getLatestTreeUpdate = `-- name: GetLatestTreeUpdate :one
SELECT tu.tree_id, tu.update_date, tu.file_id, f.file_store, f.file_store_id, f.file_path, f.file_name, f.file_type, f.file_expiration
FROM core.tree_update tu
    JOIN core.file f ON tu.file_id = f.id
WHERE
    tu.tree_id = $1
ORDER BY tu.update_date DESC
LIMIT 1
`

type GetLatestTreeUpdateRow struct {
	TreeID         string             `json:"tree_id"`
	UpdateDate     pgtype.Timestamptz `json:"update_date"`
	FileID         string             `json:"file_id"`
	FileStore      string             `json:"file_store"`
	FileStoreID    pgtype.Text        `json:"file_store_id"`
	FilePath       pgtype.Text        `json:"file_path"`
	FileName       pgtype.Text        `json:"file_name"`
	FileType       pgtype.Text        `json:"file_type"`
	FileExpiration pgtype.Timestamptz `json:"file_expiration"`
}

// Get the most recent update for a tree
func (q *Queries) GetLatestTreeUpdate(ctx context.Context, treeID string) (GetLatestTreeUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLatestTreeUpdate, treeID)
	var i GetLatestTreeUpdateRow
	err := row.Scan(
		&i.TreeID,
		&i.UpdateDate,
		&i.FileID,
		&i.FileStore,
		&i.FileStoreID,
		&i.FilePath,
		&i.FileName,
		&i.FileType,
		&i.FileExpiration,
	)
	return i, err
}
